### ISSUE TITLE
Need to add specific instructions for generating/using a GitHub Personal Access Token

### ISSUE THREAD

**Issue by omkensey** [hashicorp/field-workshops-terraform#318] opened 2021-12-16 21:26 UTC
I TA'ed a workshop today where more than one attendee had issues because when using a PAT, the "username" you need to use on a push is not your GitHub username, but the PAT, and the password is blank.  Also I had one who had nulled out all the "repo" permissions when creating the tag, so we had to fix that -- might want to add a note that the PAT's repo permissions (which I believe are default?) should not be removed.

**Comment by rberlind** [comment] 2021-12-16 23:11
I do not believe this is correct, @omkensey, if the user used the git commands given and does not do anything extra.  I believe that a user does in fact have to provide their GitHub user ID and then their PAT, not just their PAT.  And that is what the solve-workstation script for the "Version Controlled Infrastructure" challenges do.  For instance, see https://github.com/hashicorp/field-workshops-terraform/blob/main/instruqt-tracks/terraform-cloud-aws/versioned-infrastructure/solve-workstation#L31-L36.

But I will double-check manually tomorrow. It is possible that the username is not needed when a user has done some extra git setup in their VM to make it the default. In that case, the `git push` command might just prompt for the PAT, but in this case, the command is prompting for the password and the user is supposed to provide their PAT. But on my laptop, I am not prompted for the username or the PAT. So, I would think if a user did extra setup to avoid having to provide the username, they would also not need the PAT.

Can you clarify what you mant about the user nulling out the repo permissions when creating the tag?  Which exact challenge and commend are we talking about? I think you mean the git commands used in the "Terraform Compliance with Sentinel" challenge. Right? But I don't see how that would affect the repository's permissions since the git commands are these:
```
git pull
git add .
git commit -m "Added the first tag"
git push origin master
````

Perhaps you mean that they actually created their PAT https://github.com/settings/tokens while running the track and set up the PAT with the wrong permissions? But they should have done that during the "Versioned Controlled Infrastructure" challenge, not the Sentinel challenge.

I agree that we should document what permissions (scopes) are needed for the PAT. The one I use has repo and workflow scopes. We'll need to determine the bare minimum.  I don't think workflow is really needed.

**Comment by rberlind** [comment] 2021-12-17 00:14
I confirmed that the first time I do a push, I am prompted for both username and password.  I provide my PAT to the password prompt.
![Screen Shot 2021-12-16 at 7 11 35 PM](https://user-images.githubusercontent.com/23617012/146467490-6776875b-5e1e-469b-b365-31d0c68485db.png)

**Comment by rberlind** [comment] 2021-12-17 00:18
I was able to do a commit against my public fork of https://github.com/hashicorp/hashicat-aws with a PAT that only had the repo | public_repo scope.  We can update the assignments for all 3 cloud tracks to say that.

**Comment by rberlind** [comment] 2021-12-17 00:27
The docs for GH PAT scopes is done by https://github.com/hashicorp/field-workshops-terraform/pull/319

**Comment by rberlind** [comment] 2022-01-26 00:31
closing this since I addressed it.

**Closed by rberlind** 2022-01-26 00:31 UTC
